services:
  app:
    build: 
      context: ./docker/php
    container_name: solidaria_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - postgres
    networks:
      - solidaria-network
  nginx:
    image: nginx:latest
    container_name: solidaria_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - solidaria-network
  
  postgres:
    image: postgres:16.8
    container_name: solidaria_postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: solidaria
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - solidaria-network
    
  adminer:
    image: adminer:latest
    container_name: solidaria_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - solidaria-network
  node: 
    image: node:22
    container_name: solidaria_node
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: bash -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - solidaria-network
  composer:
    build: 
      context: ./docker/php
    container_name: solidaria_composer
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: bash -c "composer install"
    entrypoint: ["composer"]
    networks:
      - solidaria-network


networks:
  solidaria-network:

volumes:
  postgres_data: